test-case:
  name: Positive Test for has-configuration-management-plan
  description: Test that a SSP back-matter resource element has a configuration-management-plan element.
  content: ../content/FedRAMP-SSP-Example.OSCAL.xml
  expectations:
    - constraint-id: has-configuration-management-plan
      result: pass
